apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiz-clicker-frontend
  labels:
    app: wiz-clicker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wiz-clicker
  template:
    metadata:
      labels:
        app: wiz-clicker
    spec:
      containers:
        - name: frontend
          image: hussr98/wizclicker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
