name: Deploy to Fly.io

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --image ${{ secrets.DOCKER_HUB_USERNAME }}/wizclicker:latest
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
